name: PushOut
main: me.pushout.PushOut
version: 1.0
api-version: 1.18
commands:
  pushout:
    description: Lance une partie de PushOut
    usage: /pushout start
  pushoutconfig:
    description: Ouvre le menu de configuration de PushOut
    usage: /pushoutconfig
permissions:
  pushout.use:
    description: Permet d'utiliser le mode PushOut
    default: op
